import Head from 'next/head';
import {useRouter} from 'next/router';
import {Grid, Button} from '@material-ui/core';
import SwapCard from '../components/swapCard';
import InfoCard from '../components/infoCard';

export default function Home() {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className = "diceGrid1">
        <Grid container className = "text-center mb-5">
          <Grid item xs = {1} sm = {2} md = {4}></Grid>
          <Grid item xs = {10} sm = {8} md = {4} className = "x-home-top-container">
            <Button variant = "outlined" className = "x-home-top-button x-font3" onClick = {()=>router.push("/")}>Swap</Button>
            <Button variant = "outlined" className = "x-home-top-button x-font3" onClick = {()=>router.push("/liquidity")}>Add Liquidity</Button>
          </Grid>
          <Grid item xs = {1} sm = {2} md = {4}></Grid>
        </Grid>
        <Grid container>
          <Grid item xs = {1} sm = {2} md = {4}></Grid>
          <Grid item xs = {10} sm = {8} md = {4}>
            <SwapCard />
            {/* <div className = "mt-4">
              <InfoCard />
            </div> */}
          </Grid>
          <Grid item xs = {1} sm = {2} md = {4}></Grid>
        </Grid>
      </div>
    </div>
  )
}
